workInfo:
  title: "GPM 313. KATONG BAKUMPUUL RAME RAME"
  fullTitle: "GPM 313. KATONG BAKUMPUUL RAME RAME"
  composer: "BARTJE ISTIA"
  arranger: ""
  lyricist: "BARTJE ISTIA"
  instrument: "SATB"
  notationType: "not angka"
  workType: "Salinan" 
  workId: "GPM313_KatongBakumpulRameRame"
  movementName: "1 Suara"

files:
  audioPath: "GPM313_KatongBakumpulRameRame.mp3"

musicalStructure:
  totalDurationSeconds: 84.145
  totalMeasures: 29
  lastMeasureDuration: 4/4
  visualLeadTimeSeconds: 0.05

features:
  barHighlight: false
  noteHighlight: true